package co.vistafoundation.vlearning.subscription.model;

import java.io.Serializable;
import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "video_streaming_log")
public class VideoStreamingLog implements Serializable{
	

	/**
	 * 
	 */
	private static final long serialVersionUID = 5435601840679284263L;

	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String idVideoStreamingLog;
	
	@DynamoDBAttribute
	private Long idVlUser;
	
	@DynamoDBAttribute
	private Long idOfflineVideoCourse;
	
	@DynamoDBAttribute
	private Long idStudentAssignedCourse;
	
	@DynamoDBAttribute
	private Long idProduct;

	@DynamoDBAttribute
	private int videoCoverageDuration;
	
	@DynamoDBAttribute
	private int videoDuration;
	
	@DynamoDBAttribute
	private String pctComplete;
	
	@DynamoDBAttribute
	private Long idSubject;
	
	@DynamoDBAttribute
	private String subjectName;
	
	@DynamoDBAttribute
	private Long idSubjectChapter;
	
	@DynamoDBAttribute
	private String chapterName;
	
	@DynamoDBAttribute
	private String topic;
	
	@DynamoDBAttribute
	private String videoPoster1Location;
	
	@DynamoDBAttribute
	private String videoDescription;
	
	@DynamoDBAttribute
	private Boolean completeFlag;
	
	@DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.ALWAYS)
	private Date lastUpdatedTime;
	
	@DynamoDBAttribute
	private String category;
	
	@DynamoDBAttribute
	private int videoSeqNumber = 0;

	public VideoStreamingLog() {
		super();
	}
   
    
	public VideoStreamingLog(Long idVlUser, Long idOfflineVideoCourse, Long idStudentAssignedCourse, Long idProduct,
			int videoCoverageDuration, int videoDuration, String pctComplete, Long idSubject, String subjectName,
			Long idSubjectChapter, String chapterName, String topic, String videoPoster1Location,
			String videoDescription, Boolean completeFlag, Date lastUpdatedTime, String category, int videoSeqNumber) {
		super();
		this.idVlUser = idVlUser;
		this.idOfflineVideoCourse = idOfflineVideoCourse;
		this.idStudentAssignedCourse = idStudentAssignedCourse;
		this.idProduct = idProduct;
		this.videoCoverageDuration = videoCoverageDuration;
		this.videoDuration = videoDuration;
		this.pctComplete = pctComplete;
		this.idSubject = idSubject;
		this.subjectName = subjectName;
		this.idSubjectChapter = idSubjectChapter;
		this.chapterName = chapterName;
		this.topic = topic;
		this.videoPoster1Location = videoPoster1Location;
		this.videoDescription = videoDescription;
		this.completeFlag = completeFlag;
		this.lastUpdatedTime = lastUpdatedTime;
		this.category = category;
		this.videoSeqNumber = videoSeqNumber;
	}



	public String getIdVideoStreamingLog() {
		return idVideoStreamingLog;
	}

	public void setIdVideoStreamingLog(String idVideoStreamingLog) {
		this.idVideoStreamingLog = idVideoStreamingLog;
	}

	public Long getIdVlUser() {
		return idVlUser;
	}

	public void setIdVlUser(Long idVlUser) {
		this.idVlUser = idVlUser;
	}

	public Long getIdOfflineVideoCourse() {
		return idOfflineVideoCourse;
	}

	public void setIdOfflineVideoCourse(Long idOfflineVideoCourse) {
		this.idOfflineVideoCourse = idOfflineVideoCourse;
	}

	public Long getIdStudentAssignedCourse() {
		return idStudentAssignedCourse;
	}


	public void setIdStudentAssignedCourse(Long idStudentAssignedCourse) {
		this.idStudentAssignedCourse = idStudentAssignedCourse;
	}

	public Long getIdProduct() {
		return idProduct;
	}


	public void setIdProduct(Long idProduct) {
		this.idProduct = idProduct;
	}


	public int getVideoCoverageDuration() {
		return videoCoverageDuration;
	}

	public void setVideoCoverageDuration(int videoCoverageDuration) {
		this.videoCoverageDuration = videoCoverageDuration;
	}

	public int getVideoDuration() {
		return videoDuration;
	}

	public void setVideoDuration(int videoDuration) {
		this.videoDuration = videoDuration;
	}

	public String getPctComplete() {
		return pctComplete;
	}

	public void setPctComplete(String pctComplete) {
		this.pctComplete = pctComplete;
	}

	public Long getIdSubject() {
		return idSubject;
	}

	public void setIdSubject(Long idSubject) {
		this.idSubject = idSubject;
	}

	public String getSubjectName() {
		return subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	public Long getIdSubjectChapter() {
		return idSubjectChapter;
	}

	public void setIdSubjectChapter(Long idSubjectChapter) {
		this.idSubjectChapter = idSubjectChapter;
	}

	public String getChapterName() {
		return chapterName;
	}

	public void setChapterName(String chapterName) {
		this.chapterName = chapterName;
	}

	public String getTopic() {
		return topic;
	}

	public void setTopic(String topic) {
		this.topic = topic;
	}

	public String getVideoPoster1Location() {
		return videoPoster1Location;
	}

	public void setVideoPoster1Location(String videoPoster1Location) {
		this.videoPoster1Location = videoPoster1Location;
	}

	public String getVideoDescription() {
		return videoDescription;
	}

	public void setVideoDescription(String videoDescription) {
		this.videoDescription = videoDescription;
	}

	public Boolean getCompleteFlag() {
		return completeFlag;
	}

	public void setCompleteFlag(Boolean completeFlag) {
		this.completeFlag = completeFlag;
	}

	public Date getLastUpdatedTime() {
		return lastUpdatedTime;
	}

	public void setLastUpdatedTime(Date lastUpdatedTime) {
		this.lastUpdatedTime = lastUpdatedTime;
	}


	public String getCategory() {
		return category;
	}


	public void setCategory(String category) {
		this.category = category;
	}


	/**
	 * @return the videoSeqNumber
	 */
	public int getVideoSeqNumber() {
		return videoSeqNumber;
	}


	/**
	 * @param videoSeqNumber the videoSeqNumber to set
	 */
	public void setVideoSeqNumber(int videoSeqNumber) {
		this.videoSeqNumber = videoSeqNumber;
	}
	
	
	
}
