version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vistas-frontend
    ports:
      - "80:80"
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vistas-backend
    ports:
      - "9090:8080"
    restart: always

