@echo off
set DATASOURCE_URL=jdbc:mysql://127.0.0.1:3306/vlearning?createDatabaseIfNotExist=true^&useSSL=false^&allowPublicKeyRetrieval=true
set DATASOURCE_USERNAME=root
set DATASOURCE_PASSWORD=root
set HIBERNATE_DDL=update
set JWT_NAME=vlearning
set JWT_SECRET=vlearningSecretKey1234567890vlearningSecretKey1234567890
set JWT_EXPIRATION_INMS=86400000
set JWT_MOB_EXPIRATION_INMS=86400000
set JWT_REFRESH_INMS=2592000000
set LOCK_DURATION=300
set SES_MAIL_USERNAME=dummy
set SES_MAIL_PASSWORD=dummy
set WEBAPP_PAYMENT_URL=http://localhost:5173/payment-response
set MERCHANT_ID=dummy
set PAYTM_PAYMENT_URL=https://securegw-stage.paytm.in/order/process
set PAYTM_PAYMENT_CALLBACK_URL=http://localhost:9090/api/payment/callback
set PAYTM_INITIATE_TRANSACTION_URL=https://securegw-stage.paytm.in/theia/api/v1/initiateTransaction
set PAYTM_ORDER_STATUS_URL=https://securegw-stage.paytm.in/v3/order/status
set AWS_ACCESSKEY=dummy
set AWS_SECRETACCESS=dummy
set S3_BUCKET=dummy
set DYNAMO_DB_REGION=ap-south-1
set SMS_FLAG=false
set APP_ANGULAR_URL=http://localhost:5173
set APP_SHARE_URL=http://localhost:5173
set BE_DNS_URL=http://localhost:9090
set SHARE_VIDEO_VIEWCOUNT=5
set SHARE_VIDEO_REQUESTCOUNT=10
set SHARE_VIDEO_EXPIRY_MINUTES=60
set FCM_TOPIC=vlearning
set SWAGGER_UI_FLAG=true
set SWAGGER_API_DOCS_FLAG=true
set THREAD_CAR_POOL_SIZE=10
set THREAD_MAX_POOL_SIZE=20
set THREAD_QUEUE_CAPACITY=100
set IN_APP_PURCHASE_ISSUER_ID=dummy
set IN_APP_PURCHASE_KEY_ID=dummy
set IN_APP_PURCHASE_BUNDLE_ID=dummy
set IN_APP_PURCHASE_ENVIRONMENT=sandbox
set REDIS_CACHE_HOST=localhost
set REDIS_CACHE_PORT=6379
set SPRING_CACHE_TYPE=simple
set FIREBASE_REMOTE_CONFIG=dummy
set TEST_OTP=123456
set GOOGLE_CLIENT_ID=dummy
set GOOGLE_SERVER_KEY=dummy
set VCT_AVAILABLE_DATE=2026-05-30T16:00:00Z
set SHOW_VCT_RESULT=false
set SPRING_DATASOURCE_INITIALIZATION_MODE=never

echo Starting v-learning spring-boot backend with local profile...
"%JAVA_HOME%\bin\java.exe" -jar target\v-learning-2.2.0-SNAPSHOT.war
