package co.vistafoundation.vlearning.user_activity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;

@DynamoDBTyped
@DynamoDBTable(tableName = "user_activity")
public class UserActivity {

		
	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	String idUserActivity;
	
	@DynamoDBAttribute
	String userName;

	@DynamoDBAttribute
	Long userSurId;

	@DynamoDBAttribute
	String lastActivityTime;
	
	@DynamoDBAttribute
	String name;
	
	@DynamoDBAttribute
	String  deviceType;

	
	

	public UserActivity() {
		super();
		// TODO Auto-generated constructor stub
	}



	public UserActivity( String userName, Long userSurId, String lastActivityTime, String name,
			String deviceType) {
		super();
		this.userName = userName;
		this.userSurId = userSurId;
		this.lastActivityTime = lastActivityTime;
		this.name = name;
		this.deviceType = deviceType;
	}



	public String getIdUserActivity() {
		return idUserActivity;
	}

	public void setIdUserActivity(String idUserActivity) {
		this.idUserActivity = idUserActivity;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Long getUserSurId() {
		return userSurId;
	}

	public void setUserSurId(Long userSurId) {
		this.userSurId = userSurId;
	}



	public String getLastActivityTime() {
		return lastActivityTime;
	}



	public void setLastActivityTime(String lastActivityTime) {
		this.lastActivityTime = lastActivityTime;
	}



	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDeviceType() {
		return deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}



	@Override
	public String toString() {
		return "UserActivity [idUserActivity=" + idUserActivity + ", userName=" + userName + ", userSurId=" + userSurId
				+ ", lastActivityTime=" + lastActivityTime + ", name=" + name + ", deviceType=" + deviceType + "]";
	}
	
	
	
}
